//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Emergence.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.Emergence.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: &quot;None&quot;,
        ///    &quot;Difficulty&quot;: 0
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;Security Search&quot;,
        ///    &quot;Difficulty&quot;: 3,
        ///    &quot;Entities&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;ACTOR_SEC_AGENT&quot;,
        ///        &quot;Chance&quot;: 1,
        ///        &quot;MinQuantity&quot;: 2,
        ///        &quot;MaxQuantity&quot;: 4
        ///      }
        ///    ]
        ///  },    {
        ///    &quot;Id&quot;: &quot;Garbage Collector&quot;,
        ///    &quot;Difficulty&quot;: 3,
        ///    &quot;Entities&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;ACTOR_GARBAGE_COLLECTOR&quot;,
        ///        &quot;Chance&quot;: 1
        ///      }
        ///    ]
        ///  },  
        ///  {
        ///    &quot;Id&quot;: &quot;Security Detachment&quot;,
        ///    &quot;Difficulty&quot;: 3,
        ///    &quot;En [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Encounters {
            get {
                return ResourceManager.GetString("Encounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;none&quot;,
        ///    &quot;encounterIds&quot;: [ &quot;None&quot; ]
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;default&quot;,
        ///    &quot;encounterIds&quot;: [ &quot;Security Search&quot;, &quot;Garbage Collector&quot;, &quot;General Search&quot;, &quot;AntiVirus Patrol&quot;, &quot;Logic Bomb&quot;, &quot;Inspector Search&quot;, &quot;Help Search&quot;, &quot;Byte&quot;, &quot;Defender w Escort&quot;, &quot;Worms&quot;, &quot;BugMinor&quot;, &quot;BugSwarm&quot;, &quot;Virus&quot; ]
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;small&quot;,
        ///    &quot;encounterIds&quot;: [ &quot;Security Search&quot;, &quot;Garbage Collector&quot;, &quot;General Search&quot;, &quot;Single Daemon&quot;, &quot;Logic Bomb&quot;, &quot;Inspector Search&quot;, &quot;Byte&quot;, &quot;Defender w Escort&quot;, &quot;Worms&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncounterSets {
            get {
                return ResourceManager.GetString("EncounterSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Simple Server&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: 11, &quot;Y&quot;: 4 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Intersection&quot;,
        ///            &quot;X&quot;: 2,
        ///            &quot;Y&quot;: -8,
        ///            &quot;EncounterSet&quot;: &quot;default&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tank Room&quot;,
        ///            &quot;X&quot;: -12,
        ///            &quot;Y&quot;: -7,
        ///            &quot;EncounterSet&quot;: &quot;default&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tank Room&quot;,
        ///            &quot;X&quot;: 12,
        ///            &quot;Y&quot;: -7,
        ///            &quot;EncounterSet&quot;: &quot;default&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Smart Fridge&quot;,
        ///  &quot;Start&quot;: { &quot;X&quot;: 3, &quot;Y&quot;: -2 },
        ///  &quot;Instructions&quot;: [
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Short Vertical Hall&quot;,
        ///      &quot;X&quot;: -5,
        ///      &quot;Y&quot;: -10
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Short Vertical Hall&quot;,
        ///      &quot;X&quot;: 1,
        ///      &quot;Y&quot;: -10
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Large Hall&quot;,
        ///      &quot;X&quot;: -8,
        ///      &quot;Y&quot;: -14
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Horizontal Airlock&quot;,
        ///      &quot;X&quot;: -27,
        ///      &quot;Y&quot;: -14
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Large Hall&quot;,
        ///      &quot;X&quot;: -24,
        ///      &quot;Y&quot;: -14
        ///    },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Data Interchange&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: 2, &quot;Y&quot;: 0},
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Network Adapter&quot;,
        ///            &quot;X&quot;: -9,
        ///            &quot;Y&quot;: -4,
        ///            &quot;EncounterSet&quot;: &quot;none&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Vertical Airlock&quot;,
        ///            &quot;X&quot;: -14,
        ///            &quot;Y&quot;: -14
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Vertical Airlock&quot;,
        ///            &quot;X&quot;: 6,
        ///            &quot;Y&quot;: -14
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Elbow Corrido [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Bastion System&quot;,
        ///  &quot;Start&quot;: { &quot;X&quot;: -20, &quot;Y&quot;: 31 },
        ///  &quot;Instructions&quot;: [
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Widening Corridor&quot;,
        ///      &quot;X&quot;: -29,
        ///      &quot;Y&quot;: 23
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Widening Corridor&quot;,
        ///      &quot;X&quot;: -2,
        ///      &quot;Y&quot;: -17,
        ///      &quot;FlipY&quot;: true
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Connector Bus&quot;,
        ///      &quot;X&quot;: -27,
        ///      &quot;Y&quot;: 11
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Connector Bus&quot;,
        ///      &quot;X&quot;: -18,
        ///      &quot;Y&quot;: -13
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Intersection&quot;,
        ///      &quot;X&quot;: -60,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Router Gateway&quot;,
        ///  &quot;Start&quot;: {&quot;X&quot;: 5, &quot;Y&quot;:  2},
        ///  &quot;Instructions&quot;: [
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Network In-Only&quot;,
        ///      &quot;X&quot;: 0,
        ///      &quot;Y&quot;: 0,
        ///      &quot;EncounterSet&quot;: &quot;none&quot;
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Tank Room&quot;,
        ///      &quot;X&quot;: -14,
        ///      &quot;Y&quot;: -1
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Pillar Room&quot;,
        ///      &quot;X&quot;: -24,
        ///      &quot;Y&quot;: -3
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;Airlock&quot;,
        ///      &quot;X&quot;: -21,
        ///      &quot;Y&quot;: 7
        ///    },
        ///    {
        ///      &quot;PrefabId&quot;: &quot;AirlockHForceField&quot;,
        ///      &quot;X&quot;: -28,
        ///      &quot;Y&quot;: 0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LevelBoss {
            get {
                return ResourceManager.GetString("LevelBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Door Test&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: 2, &quot;Y&quot;: 2 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Test_Doors&quot;,
        ///            &quot;X&quot;: 0,
        ///            &quot;Y&quot;: 0,
        ///            &quot;EncounterSet&quot;: &quot;none&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string LevelDoorsTest {
            get {
                return ResourceManager.GetString("LevelDoorsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Training Dual Rooms&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: 9, &quot;Y&quot;: 1 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;TrainDualRooms&quot;,
        ///            &quot;X&quot;: 0,
        ///            &quot;Y&quot;: 0,
        ///            &quot;EncounterSet&quot;: &quot;None&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string LevelTrainDualRooms {
            get {
                return ResourceManager.GetString("LevelTrainDualRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Training FriendlyFire&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: 1, &quot;Y&quot;: 1 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;TrainFriendlyFire&quot;,
        ///            &quot;X&quot;: 0,
        ///            &quot;Y&quot;: 0,
        ///            &quot;EncounterSet&quot;: &quot;None&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string LevelTrainFriendlyFireRoom {
            get {
                return ResourceManager.GetString("LevelTrainFriendlyFireRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Training&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: -17, &quot;Y&quot;: -12 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Training&quot;,
        ///            &quot;X&quot;: -24,
        ///            &quot;Y&quot;: -36,
        ///            &quot;EncounterSet&quot;: &quot;Training&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string LevelTraining {
            get {
                return ResourceManager.GetString("LevelTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Training Single Room&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: 7, &quot;Y&quot;: 2 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;TrainSingleRoom&quot;,
        ///            &quot;X&quot;: 0,
        ///            &quot;Y&quot;: 0,
        ///            &quot;EncounterSet&quot;: &quot;None&quot;
        ///        }
        ///    ]
        ///}
        ///    .
        /// </summary>
        internal static string LevelTrainSingleRoom {
            get {
                return ResourceManager.GetString("LevelTrainSingleRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Tutorial&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: -14, &quot;Y&quot;: 44 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tutorial_Start&quot;,
        ///            &quot;X&quot;: -17,
        ///            &quot;Y&quot;: 41,
        ///            &quot;EncounterSet&quot;: &quot;none&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tutorial_CharacterSelect1&quot;,
        ///            &quot;X&quot;: -23,
        ///            &quot;Y&quot;: 38,
        ///            &quot;EncounterSet&quot;: &quot;none&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tutorial_CharacterSelect2&quot;,
        ///            &quot;X&quot;: -29,
        ///            &quot;Y&quot;: 38,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LevelTutorial {
            get {
                return ResourceManager.GetString("LevelTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: &quot;Network Adapter&quot;,
        ///    &quot;IsInvulnerable&quot;: true,
        ///    &quot;Data&quot;: [
        ///      &quot;  ##+#####+##  &quot;,
        ///      &quot;  #.,..#..,.#  &quot;,
        ///      &quot;  #.,.###.,.#  &quot;,
        ///      &quot;###.,..,..,.###&quot;,
        ///      &quot;#&gt;|,,,,,,,,,|&lt;# &quot;,
        ///      &quot;###.........###&quot;,
        ///      &quot;  ##.......##  &quot;,
        ///      &quot;  ########### &quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;Network In-Only&quot;,
        ///    &quot;IsInvulnerable&quot;: true,
        ///    &quot;Data&quot;: [
        ///      &quot;###+### &quot;,
        ///      &quot;#..,..###&quot;,
        ///      &quot;+..,,,|&lt;# &quot;,
        ///      &quot;#..,..###&quot;,
        ///      &quot;###+### &quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;Test [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prefabs {
            get {
                return ResourceManager.GetString("Prefabs", resourceCulture);
            }
        }
    }
}
