//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Emergence.LevelData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.Emergence.LevelData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Tutorial&quot;,
        ///    &quot;Start&quot;: { &quot;X&quot;: -14, &quot;Y&quot;: 44 },
        ///    &quot;Instructions&quot;: [
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tutorial_Start&quot;,
        ///            &quot;X&quot;: -17,
        ///            &quot;Y&quot;: 41,
        ///            &quot;EncounterSet&quot;: &quot;none&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tutorial_CharacterSelect1&quot;,
        ///            &quot;X&quot;: -23,
        ///            &quot;Y&quot;: 38,
        ///            &quot;EncounterSet&quot;: &quot;none&quot;
        ///        },
        ///        {
        ///            &quot;PrefabId&quot;: &quot;Tutorial_CharacterSelect2&quot;,
        ///            &quot;X&quot;: -29,
        ///            &quot;Y&quot;: 38,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level0 {
            get {
                return ResourceManager.GetString("Level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: &quot;Network Adapter&quot;,
        ///    &quot;IsInvulnerable&quot;: true,
        ///    &quot;Data&quot;: [
        ///      &quot;  ##+#####+##  &quot;,
        ///      &quot;  #.,..#..,.#  &quot;,
        ///      &quot;  #.,.###.,.#  &quot;,
        ///      &quot;###.,..,..,.###&quot;,
        ///      &quot;#&gt;|,,,,,,,,,|&lt;# &quot;,
        ///      &quot;###.........###&quot;,
        ///      &quot;  ##.......##  &quot;,
        ///      &quot;  ########### &quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;Network In-Only&quot;,
        ///    &quot;IsInvulnerable&quot;: true,
        ///    &quot;Data&quot;: [
        ///      &quot;###+### &quot;,
        ///      &quot;#..,..###&quot;,
        ///      &quot;+..,,,|&lt;# &quot;,
        ///      &quot;#..,..###&quot;,
        ///      &quot;###+### &quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;Test [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prefabs {
            get {
                return ResourceManager.GetString("Prefabs", resourceCulture);
            }
        }
    }
}
