namespace MattEland.Emergence.AI.Sensory
{
    public enum CellAspectType
    {
        Corruption,
        Corruptable,
        Capturable,
        Destructable,
        Actor,
        Ally,
        Enemy,
        Player,
        Door,
        Core,
        //Help,
        Firewall,
        //Service,
        Turret,
        Self,
        HasObstacle,
        CurrentHealth,
        CurrentOps,
        RandomFactor,
        CoresControlled,
        /*
        Cabling,
        CommandPickup,
        Debris,
        DataStore,
        Divider,
        Treasure,
        Entrance,
        Exit,
        StabilityPickup,
        OpsPickup,
         */
    }
}